## Copyright 2022 Intel Corporation
## SPDX-License-Identifier: Apache-2.0

name: continuous

permissions: read-all

on: [push, workflow_dispatch]

jobs:
  ################################################################################
  ################################################################################
  # GPU tests
  ################################################################################
  ###############################################################################
  
  ########################################
  # Linux DG2
  ########################################
  ubuntu24-build:
    secrets: inherit
    uses: intel-innersource/libraries.devops.renderkit.workflows/.github/workflows/docker.yml@main
    with:
      image: embree/ubuntu:24.04
      runs-on: '[ "Linux", "docker", "build" ]'
      project: embree
      dpcpp-version: intel-llvm/sycl-rel_5_2_0-rk
      artifact-out: ubuntu24-build
      artifact-path: ./build/*.tar.gz
      cmd: |
        module load cmake/3.25.3
        cmake --preset linux-DG2-JIT-INTERNAL -DCMAKE_BUILD_TYPE=Release -DEMBREE_TESTING_INTENSITY=3
        cmake --build build --config Release --target build

  ubuntu24-test:
    secrets: inherit
    uses: intel-innersource/libraries.devops.renderkit.workflows/.github/workflows/docker.yml@main
    needs: ["ubuntu24-build"]
    with:
      image: embree/ubuntu:24.04
      options: --device=/dev/dri:/dev/dri
      runs-on: '[ "Linux", "docker", "dg2" ]'
      project: embree
      env-from-files: ./.github/workflows/gfx-ubuntu24-internal.env
      dpcpp-version: intel-llvm/sycl-rel_5_2_0-rk
      artifact-in: ubuntu24-build
      cmd: |
        module load cmake/3.25.3
        cmake --preset linux-DG2-JIT-INTERNAL -DCMAKE_BUILD_TYPE=Release -DEMBREE_TESTING_INTENSITY=3
        cmake --build build --config Release --target test_package


  ubuntu22-build:
    secrets: inherit
    uses: intel-innersource/libraries.devops.renderkit.workflows/.github/workflows/docker.yml@main
    with:
      image: embree/ubuntu:22.04
      runs-on: '[ "Linux", "docker", "build" ]'
      project: embree
      dpcpp-version: intel-llvm/sycl-rel_5_2_0-rk
      artifact-out: ubuntu22-build
      artifact-path: ./build/*.tar.gz
      cmd: |
        module load cmake/3.25.3
        cmake --preset linux-DG2-JIT-INTERNAL -DCMAKE_BUILD_TYPE=Release -DEMBREE_TESTING_INTENSITY=3
        cmake --build build --config Release --target build

  ubuntu22-test:
    secrets: inherit
    uses: intel-innersource/libraries.devops.renderkit.workflows/.github/workflows/docker.yml@main
    needs: ["ubuntu22-build"]
    with:
      image: embree/ubuntu:22.04
      options: --device=/dev/dri:/dev/dri
      runs-on: '[ "Linux", "docker", "dg2" ]'
      project: embree
      env-from-files: ./.github/workflows/gfx-ubuntu22-internal.env
      dpcpp-version: intel-llvm/sycl-rel_5_2_0-rk
      artifact-in: ubuntu22-build
      cmd: |
        module load cmake/3.25.3
        cmake --preset linux-DG2-JIT-INTERNAL -DCMAKE_BUILD_TYPE=Release -DEMBREE_TESTING_INTENSITY=3
        cmake --build build --config Release --target test_package